import styles from './page.module.css'
import DemoService from '@/services/demo';
import { Button } from '@mui/base/Button';
import {Metadata} from 'next';

export const metadata: Metadata = {
    title: 'ChatGPT',
    description: 'Generated by create next app',
}

export default function Demo() {
  const config = DemoService.get('chatgpt');
  return (
    <div>
        <h1>{config.title}</h1>
        <Button>Click Me</Button>
    </div>
  )
}
