import DemoService from '@/services/demo';
import Layout from '@/components/layout';
import * as React from 'react';
import {Metadata} from 'next';
import DemoWrapper from '@/components/demo-wrapper';
import DemoHeader from '@/components/demo-header';
import Demo from './demo';

export const metadata: Metadata = {
    title: 'ChatGPT',
    description: 'Generated by create next app',
}

export default async function DemoPage() {
  const config = DemoService.get('chatgpt');
  return (
    <Layout top={<DemoHeader demo={config} />}>
        <DemoWrapper demo={config}>
            <Demo />
        </DemoWrapper>
    </Layout>
  )
}



